### ISSUE TITLE
README seem to refer to wrong script

### ISSUE THREAD

**Issue by WilliamH-RCM** [meowcat/MassBank-convert#2]
Using the package seems pretty easy and straight forward, but ran into trouble when converting from the sqlite database to an mzVault database. I then realised both of the conversions in the README use the same script "/scripts/sqlite/gen_sqlite.sh"

It is a very simply solution, just change to "/scripts/mzvault/gen_mzvault.sh" for the second conversion mentioned and you're golden!

**Comment by meowcat** [comment]
Hi, thanks for noticing! can you PR?

**Comment by WilliamH-RCM** [comment]
I'm very new to this, but it should be working now
